### ISSUE TITLE
sympy ImportError: cannot import name 'with_metaclass' from 'sympy.core.compatibility'

### ISSUE THREAD

**Issue by arnedecadt** [ShaharGottlieb/MasseyRamanujan#26]
Which version of sympy has to be used? I am getting the following error while trying to run scripts/paper_results/e_results:
```
The sympy.core.compatibility submodule is deprecated.

This module was only ever intended for internal use. Some of the functions
that were in this module are available from the top-level SymPy namespace,
i.e.,

    from sympy import ordered, default_sort_key

The remaining were only intended for internal SymPy use and should not be used
by user code.

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-sympy-core-compatibility
for details.

This has been deprecated since SymPy version 1.10. It
will be removed in a future version of SymPy.

  from sympy.core.compatibility import with_metaclass
Traceback (most recent call last):
  File "/Users/arnedecadt/Documents/func/e_results.py", line 1, in <module>
    from ramanujan.LHSHashTable import LHSHashTable
  File "/Users/arnedecadt/Documents/func/RamanujanMachine/ramanujan/LHSHashTable.py", line 12, in <module>
    from ramanujan.constants import g_N_initial_search_dps
  File "/Users/arnedecadt/Documents/func/RamanujanMachine/ramanujan/constants.py", line 2, in <module>
    from sympy.core.compatibility import with_metaclass
ImportError: cannot import name 'with_metaclass' from 'sympy.core.compatibility' (/Users/arnedecadt/micromamba/lib/python3.9/site-packages/sympy/core/compatibility.py)
[Finished in 1.2s with exit code 1]
```

**Comment by Leonardo-coder** [comment]
We should add a requirements file so this doesn't happen again

Yaron Hadad
http://www.yaronhadad.com/

**Comment by suryanshshekhawat** [comment]
## 1. Use an Older Version of `sympy`
1. Open your CLI and run:
   ```sh
   pip uninstall sympy
   pip install sympy==1.10.1
   ```
2. Verify the installation by running:
   ```sh
   pip list
   ```
   Ensure that **`sympy`** is listed as **version 1.10.1**.

---

## 2. Modify `constants.py`
Replace the existing code in **`RamanujanMachine/ramanujan/constants.py`** with the following:

```python
import sympy
from sympy.core.singleton import Singleton
from sympy.core import NumberSymbol
import mpmath

def with_metaclass(meta, *bases):
    """
    Create a base class with a metaclass.

    This function mimics the functionality of the deprecated
    sympy.core.compatibility.with_metaclass, which is no longer available in newer Sympy versions.
    """
    return meta("NewBase", bases, {})

class Khinchin(with_metaclass(Singleton, NumberSymbol)):
    is_real = True
    is_positive = True
    is_negative = False
    is_irrational = None
    is_number = True

    mpf_val = mpmath.khinchin  # Hackish trick, used in EnumerationOverGCF.__init__

    def __str__(self):
        return 'K'

    def _latex(self, printer):
        return r"\\Kai"

sympy.S.register(Khinchin)

g_N_verify_terms = 1000  # Number of CF terms to calculate in __refine_results. (verify hits)
g_N_verify_compare_length = 100  # Number of digits to compare in __refine_results. (verify hits)
g_N_verify_dps = 2000  # Working decimal precision in __refine_results. (verify hits)
g_N_initial_search_terms = 32  # Number of CF terms to calculate in __first_enumeration (initial search)
g_N_initial_key_length = 10  # Number of digits to compare in __first_enumeration (initial search)
g_N_initial_search_dps = 50  # Working decimal precision in __refine_results. (verify hits)

g_const_dict = {
    'zeta': sympy.zeta,
    'e': sympy.E,
    'pi': sympy.pi,
    'pi_squared': sympy.pi ** 2,
    'catalan': sympy.Catalan,
    'golden_ratio': sympy.GoldenRatio,
    'khinchin': sympy.S.Khinchin,
    'euler-mascheroni': sympy.EulerGamma,
    'pi-acosh_2': sympy.pi * sympy.acosh(2),
    'polygamma': sympy.polygamma
}
```

---

## Final Check
After completing both fixes (using **Sympy 1.10.1** and updating **`constants.py`**), rerun your script. The issue should now be resolved. 

Let me know if you need further assistance!
